"""add user model

Revision ID: 11120bc2540a
Revises: e5cab27f92e0
Create Date: 2022-07-29 00:49:06.868054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11120bc2540a'
down_revision = 'e5cab27f92e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
