"""add image field to dish

Revision ID: 2e8818b11deb
Revises: 11120bc2540a
Create Date: 2022-08-10 15:48:51.730099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8818b11deb'
down_revision = '11120bc2540a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('image_path', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'image_path')
    # ### end Alembic commands ###
